# Generated by Django 5.1 on 2024-08-19 14:18

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='نام')),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50, verbose_name='نام')),
                ('last_name', models.CharField(max_length=50, verbose_name='نام خانوادگی')),
                ('email', models.EmailField(max_length=254, verbose_name='ایمیل')),
                ('phone', models.CharField(max_length=20, verbose_name='شماره تلفن')),
                ('address', models.CharField(max_length=100, verbose_name='آدرس')),
                ('zipcode', models.CharField(max_length=10, verbose_name='کد پستی')),
                ('city', models.CharField(max_length=20, verbose_name='شهر')),
                ('country', models.CharField(max_length=20, verbose_name='کشور')),
                ('password', models.CharField(max_length=20, verbose_name='رمز عبور')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='نام')),
                ('description', models.TextField(verbose_name='توضیحات')),
                ('price', models.IntegerField(verbose_name='قیمت')),
                ('image', models.ImageField(upload_to='image/products/', verbose_name='تصویر')),
                ('category', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='store.category', verbose_name='دسته بندی')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=1, verbose_name='تعداد')),
                ('address', models.CharField(blank=True, default='', max_length=200, verbose_name='آدرس')),
                ('phone', models.CharField(blank=True, default='', max_length=20, verbose_name='شماره تلفن')),
                ('date', models.DateField(default=datetime.datetime.today, verbose_name='تاریخ')),
                ('status', models.BooleanField(default=False, verbose_name='وضعیت')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.customer', verbose_name='مشتری')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.product', verbose_name='محصول')),
            ],
        ),
    ]
